### 1. Testar cadastro de cpf errado
POST http://localhost:3000/ciclista
Content-Type: application/json

{
    "nome": "Santiago",
    "email": "santiagofidmay@gmail.com",
    "senha": "abc",
    "cpf": "123456789",
    "endereco": "rua abc, 5",
    "celular": "47992884145"
}

### 2. Testar cadastro do ciclista
POST http://localhost:3000/ciclista
Content-Type: application/json

{
    "nome": "Santiago",
    "email": "santiagofidmay@gmail.com",
    "senha": "abc",
    "cpf": "12345678912",
    "endereco": "rua abc, 5",
    "celular": "47992884145"
}

### 3. Testar cadastro do ciclista
POST http://localhost:3000/ciclista
Content-Type: application/json

{
    "nome": "Sara",
    "email": "sara@gmail.com",
    "senha": "abc",
    "cpf": "12345678912",
    "endereco": "rua abc, 5",
    "celular": "47992884145"
}

### 4. Testar cadastro do ciclista
POST http://localhost:3000/ciclista
Content-Type: application/json

{
    "nome": "ana",
    "email": "ana@gmail.com",
    "senha": "abc",
    "cpf": "12345678912",
    "endereco": "rua abc, 5",
    "celular": "47992884145"
}

### 5. Testar cadastro do ciclista
POST http://localhost:3000/ciclista
Content-Type: application/json

{
    "nome": "matheus",
    "email": "matheus@gmail.com",
    "senha": "abc",
    "cpf": "12345678912",
    "endereco": "rua abc, 5",
    "celular": "47992884145"
}


### 6. FAzer Login do ciclista (Armazena o token automaticamente)
# @name loginReq
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "ana@gmail.com",
    "senha": "abc"
}